### ISSUE TITLE
Issue installing this in home assistant

### ISSUE THREAD

**Issue by tails4e** [MTrab/pyworxcloud#110] opened 2023-02-25 14:08 UTC
I tried to install v3 in home assistant, via the landroid_cloud integration - but it failed to install.
It seems the issue is due to awscrt, and by association awsiot which provides the mqtt capability.

Is awscrt (via awsiotsdk) required? I am able to manually install awsiot, but when I try install awsiotsdk, it pulls in awscrt and I get the following:

Collecting awscrt
  Using cached awscrt-0.16.10.tar.gz (21.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: awscrt
  Building wheel for awscrt (setup.py): started
  Building wheel for awscrt (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/websocket.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/s3.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/mqtt5.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/io.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/http.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/crypto.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/common.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/checksums.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/auth.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/_test.py -> build/lib.linux-x86_64-cpython-310/awscrt
      copying awscrt/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt
      creating build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 348, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 255, in run
          self._build_dependencies(dep_build_dir, dep_install_path)
        File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 247, in _build_dependencies
          self._build_dependencies_impl(build_dir, install_path)
        File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 158, in _build_dependencies_impl
          cmake = get_cmake_path()
        File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 121, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt

so it appears to need cmake, which is not part of HA

Can the dependency on awscrt be removed, if it is not strictly required for awsiot to function ?

**Comment by MTrab** [comment] 2023-02-25 16:12
If you read the frontpage of landroid_cloud, the whole thing is broken right now.And the current version of this module only have very little functionality.Await landroid_cloud v3, then all will be working againMed venlig hilsen / Regards,Malene Trab25. feb. 2023 15.09 skrev tails4e ***@***.***>:

I tried to install this in home assistant, via the landroid_cloud integration - but it failed to install.

It seems the issue is due to awscrt, and by association awsiot which provides the mqtt capability.

Is awscrt required? I am able to manually install awsiot, but when I try install awscrt I get the following:

Collecting awscrt

Using cached awscrt-0.16.10.tar.gz (21.9 MB)

Preparing metadata (setup.py): started

Preparing metadata (setup.py): finished with status 'done'

Building wheels for collected packages: awscrt

Building wheel for awscrt (setup.py): started

Building wheel for awscrt (setup.py): finished with status 'error'

error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.

│ exit code: 1

╰─> [67 lines of output]

running bdist_wheel

running build

running build_py

creating build

creating build/lib.linux-x86_64-cpython-310

creating build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/websocket.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/s3.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/mqtt5.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/mqtt.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/io.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/http.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/exceptions.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/crypto.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/common.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/checksums.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/auth.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/_test.py -> build/lib.linux-x86_64-cpython-310/awscrt

copying awscrt/init.py -> build/lib.linux-x86_64-cpython-310/awscrt

creating build/lib.linux-x86_64-cpython-310/awscrt/eventstream

copying awscrt/eventstream/rpc.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream

copying awscrt/eventstream/init.py -> build/lib.linux-x86_64-cpython-310/awscrt/eventstream

running build_ext

Traceback (most recent call last):

File "", line 2, in 

File "", line 34, in 

File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 348, in 

setuptools.setup(

File "/usr/local/lib/python3.10/site-packages/setuptools/init.py", line 87, in setup

return distutils.core.setup(**attrs)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup

return run_commands(dist)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands

dist.run_commands()

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands

self.run_command(cmd)

File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command

super().run_command(command)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command

cmd_obj.run()

File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run

self.run_command('build')

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command

self.distribution.run_command(command)

File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command

super().run_command(command)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command

cmd_obj.run()

File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run

super().run()

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run

self.run_command(cmd_name)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command

self.distribution.run_command(command)

File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command

super().run_command(command)

File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command

cmd_obj.run()

File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 255, in run

self._build_dependencies(dep_build_dir, dep_install_path)

File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 247, in _build_dependencies

self._build_dependencies_impl(build_dir, install_path)

File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 158, in _build_dependencies_impl

cmake = get_cmake_path()

File "/tmp/pip-install-i36yyhey/awscrt_dc0d744314454142b16be4fa750afda1/setup.py", line 121, in get_cmake_path

raise Exception("CMake must be installed to build from source.")

Exception: CMake must be installed to build from source.

[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

ERROR: Failed building wheel for awscrt

so it appears to need cmake, which is not part of HA

Can the dependency on awscrt be removed, if it is not strictly required for awsiot to function ?

**Comment by tails4e** [comment] 2023-02-25 16:32
Thanks, yes I did read that landroid cloud was broken, but my post was also highlighting that when this is released for v3, there may be issues due to awsiotsdk being a dependency. Simply changing the dependency to aswiot should resolve things though.

**Comment by MTrab** [comment] 2023-02-25 16:45
This will all be solved when I get the time to make the changes. Unfortunately I don't have much spare time right nowMed venlig hilsen / Regards,Malene Trab25. feb. 2023 17.32 skrev tails4e ***@***.***>:
Thanks, yes I did read that landroid cloud was broken, but my post was also highlighting that when this is released for v3, there may be issues due to awsiotsdk being a dependency. Simply changing the dependency to aswiot should resolve things though.

**Comment by MTrab** [comment] 2023-04-15 21:25
Should be fixed in 3.1.0 which should be up shortly

**Closed by MTrab** 2023-04-15 21:25 UTC
